name: Run Python Script

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt  # If your script has dependencies

      - name: Run the script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Setting token as an environment variable
        run: |
          python scripts/ktcpull.py
